version: "2"
services:
  db:
#    restart: always
    image: sameersbn/postgresql:9.6-2
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - DB_USER=chu23
      - DB_PASS=Stickerdunk1..
      - DB_NAME=rentIT
      - DB_TEMPLATE=
      - DB_EXTENSION=
      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=
    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql
  web:
    image: "rent-it-app"
    ports:
      - "8089:8089"
    depends_on:
      - db