spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/rentIT
        username: postgres
        password: root
        driverClassName: org.postgresql.Driver

    jpa:
        databasePlatform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            show_sql: true
            ddl-auto: update

    jwt:
        secret: AmUnSecretMareDeTotPeCareNuIlSpunNimanuiDelocNiciodataGhicesteSiNuVeiAfla239090932091
        tokenValidityInSeconds: 3600